### ISSUE TITLE
How do you compile the app for linux?

### ISSUE THREAD

**Issue by Tartarus6** [WhoStoleMyCoffee/kfiles#2]
I feel like im just missing something obvious, but ive never dealt with rust before.

I have `rustc`, i just dont know what to do to build the app into an executable binary file.

**Comment by WhoStoleMyCoffee** [comment]
Hi!
If you have `rustc` you likely also have `cargo`.
Run `cargo run` to run the project in debug mode. The binary will be built in the `target/debug` directory. (To build without running, it’s `cargo build`)
You can also run with `--release` to build in release mode with optimizations.

**Comment by Tartarus6** [comment]
thanks so much. this project is cool
